FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN apk --no-cache add curl git openssl

RUN yarn install 

COPY . .

RUN npx prisma generate

RUN npx tsc -p ./tsconfig.json

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

CMD ["node", "./.dist/server.js"]
