# docker-compose.yml
version: "2"

services:
  # redis:
  #   image: redis
  #   container_name: redis-karma-gap-indexer
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - '/data:/etc/redis/data'
  #   command: redis-server --appendonly yes & chmod 777 -rf /etc/redis/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: karma-gap-indexer
    ports:
      - "3001:3001"
    command: yarn prod
